Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@smorenorave 
smorenorave
/
protobootapp
Public
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
protobootapp/buildspec.yml

leonj Added mvn install to the buildspec
Latest commit d0ccac8 on 22 Oct 2021
 History
 0 contributors
64 lines (63 sloc)  1.44 KB
   
version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  build:
    commands:
      - python main.py
      # - command
  
