version: 0.2

phases:
  install:
    commands:
       - yum install -y python3
       - sudo yum install python3-pandas
       - yum install python3-numpy
       - yum install python3-scipy
  build:
    commands:
      - python3 main.py
