version: 0.2

phases:
  install:
    commands:
       - yum install -y python3
       - pip3 install -r requirements.txt

  build:
    commands:
      - python3 application.py
artifacts:
  files:
   - '**/*'
